version: "3.8"

services:
  redis:
    image: redis:6.2.7
    container_name: ms-redis
    volumes:
      - ${MS_BASE}/etc/redis/redis.conf:/etc/redis/redis.conf
      - ms-redis-data:/data
    command: redis-server /etc/redis/redis.conf --requirepass ${MS_REDIS_PASSWORD}
    networks:
      - ms-network
    restart: always
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 5s
      retries: 10
  ms-server:
    depends_on:
      redis:
        condition: service_healthy

volumes:
  ms-redis-data:
